### PR TITLE
[Fix] tokenList rearrangement by dragging

### LINKED ISSUE #185: Manual rearranging suddenly behaves differently? Exchanges items!
I suddenly see a very annoying behavior that WILL make me abandon this tool I loved so much soon, if not fixed... :-(

When I want to rearrange entries, I used to "tap" and keep-tapped an entry, then move to some other place where I wanted to insert this entry, and then release the entry.

Unfortunately, this no longer works that way. It seems that wherever I drag something, the item at the new place and the original item exchange their positions... ;-(

To elaborate, let's say we have the following:

`R-A-C-S-T-Z`

I want to drag "R" to the proper place so that everything is alphabetically sorted again.

I drag "R" to the place between "C" and "S". "R" will then be at the proper place, but "C" or "S" will suddenly be at the first position. :-(

Like this:

`C-A-R-S-T-Z`

I'm using this fine tool since years, but I've never seen such a weird behavior before... ;-(

Any idea, please?

### PR DESCRIPTION
**Pull request by PhilKes**
fixes #185 

With this commit, instead of comiting every movement of a token during a drag to the DB, a List of token-moves are stored during a drag. Once a drag action is finished the `clearView` method is called (see [ItemTouchHelper.Callback#clearView](https://developer.android.com/reference/androidx/recyclerview/widget/ItemTouchHelper.Callback#clearView(androidx.recyclerview.widget.RecyclerView,%20androidx.recyclerview.widget.RecyclerView.ViewHolder))). In this method all tracked token-moves are comitted in 1 transaction to the DB.
Also the delay of the moveRunnable was removed, which leads to a fluent execution of the drag action.

fix-rearrange-token

### CODE REVIEW

**Comment by helloworld1** [comment]
Wow, nice finding! Will test and review  the code

File: app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt [hunk 1]
```diff
@@ -17,31 +16,38 @@ class TokenTouchCallback(private val lifecycleOwner: LifecycleOwner,
...
         return true
     }
 
+    /**
+     * Is called after finishing or cancelling a drag/swipe (only called once per drag)
+     */
+    override fun clearView(recyclerView: RecyclerView, viewHolder: RecyclerView.ViewHolder) {
+        lifecycleOwner.lifecycleScope.launch {
+            optTokenDatabase.otpTokenDao().movePairs(movePairs)
+            movePairs.clear()
```
Comment (helloworld1) [inline app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt:45]: This may have a race with the movePairs.add() code above. This may happen if the DB is updating while the user start to move another token. This can result in a concurrentModificationException. I think some proper locking / thread safe collection should be used.

**Review by helloworld1 — COMMENTED** [review]
Nicely done. I have one comment about thread safety.

File: app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt (hunk 1 above)
Comment (PhilKes) [reply app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt:45]: Good point, will fix that soon.

Comment (helloworld1) [reply app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt:45]: Thanks!

Comment (PhilKes) [reply app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt]: So I now changed it to use a [CopyOnWriteArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) which is thread-safe. When iterating through the list, CopyOnWriteArrayList returns a snapshot of the list which means no ConcurrentModificationException can be thrown.
The `movePairs` List is cleared at the start of a drag.

Comment (helloworld1) [reply app/src/main/java/org/fedorahosted/freeotp/ui/TokenTouchCallback.kt]: Thanks for addressing the issue!
